"""Add onSale field to Product model

Revision ID: 4c20cf7a0bd9
Revises: 
Create Date: 2024-10-19 23:15:05.536239

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4c20cf7a0bd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onSale', sa.Boolean(), nullable=True))
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('price',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('onSale')

    # ### end Alembic commands ###
